// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Chat.proto
// Protobuf C++ Version: 5.29.3

#include "Chat.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace packet {

inline constexpr ChatRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        errorcode_{static_cast< ::packet::ErrorCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ChatRes::ChatRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChatResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatResDefaultTypeInternal() {}
  union {
    ChatRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatResDefaultTypeInternal _ChatRes_default_instance_;

inline constexpr ChatReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ChatReq::ChatReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChatReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatReqDefaultTypeInternal() {}
  union {
    ChatReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatReqDefaultTypeInternal _ChatReq_default_instance_;

inline constexpr ChatNot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sessionid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ChatNot::ChatNot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChatNotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChatNotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChatNotDefaultTypeInternal() {}
  union {
    ChatNot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChatNotDefaultTypeInternal _ChatNot_default_instance_;
}  // namespace packet
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Chat_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Chat_2eproto = nullptr;
const ::uint32_t
    TableStruct_Chat_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::ChatReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::ChatReq, _impl_.desc_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::ChatRes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::ChatRes, _impl_.errorcode_),
        PROTOBUF_FIELD_OFFSET(::packet::ChatRes, _impl_.desc_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::ChatNot, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::ChatNot, _impl_.sessionid_),
        PROTOBUF_FIELD_OFFSET(::packet::ChatNot, _impl_.desc_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::packet::ChatReq)},
        {9, -1, -1, sizeof(::packet::ChatRes)},
        {19, -1, -1, sizeof(::packet::ChatNot)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::packet::_ChatReq_default_instance_._instance,
    &::packet::_ChatRes_default_instance_._instance,
    &::packet::_ChatNot_default_instance_._instance,
};
const char descriptor_table_protodef_Chat_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nChat.proto\022\006packet\032\013Enums.proto\"\027\n\007Cha"
    "tReq\022\014\n\004desc\030\001 \001(\t\"=\n\007ChatRes\022$\n\terrorCo"
    "de\030\001 \001(\0162\021.packet.ErrorCode\022\014\n\004desc\030\002 \001("
    "\t\"*\n\007ChatNot\022\021\n\tsessionId\030\001 \001(\004\022\014\n\004desc\030"
    "\002 \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Chat_2eproto_deps[1] =
    {
        &::descriptor_table_Enums_2eproto,
};
static ::absl::once_flag descriptor_table_Chat_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Chat_2eproto = {
    false,
    false,
    173,
    descriptor_table_protodef_Chat_2eproto,
    "Chat.proto",
    &descriptor_table_Chat_2eproto_once,
    descriptor_table_Chat_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_Chat_2eproto::offsets,
    file_level_enum_descriptors_Chat_2eproto,
    file_level_service_descriptors_Chat_2eproto,
};
namespace packet {
// ===================================================================

class ChatReq::_Internal {
 public:
};

ChatReq::ChatReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.ChatReq)
}
inline PROTOBUF_NDEBUG_INLINE ChatReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::ChatReq& from_msg)
      : desc_(arena, from.desc_),
        _cached_size_{0} {}

ChatReq::ChatReq(
    ::google::protobuf::Arena* arena,
    const ChatReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChatReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:packet.ChatReq)
}
inline PROTOBUF_NDEBUG_INLINE ChatReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : desc_(arena),
        _cached_size_{0} {}

inline void ChatReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ChatReq::~ChatReq() {
  // @@protoc_insertion_point(destructor:packet.ChatReq)
  SharedDtor(*this);
}
inline void ChatReq::SharedDtor(MessageLite& self) {
  ChatReq& this_ = static_cast<ChatReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.desc_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ChatReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ChatReq(arena);
}
constexpr auto ChatReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ChatReq),
                                            alignof(ChatReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ChatReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ChatReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ChatReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ChatReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ChatReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ChatReq>(), &ChatReq::ByteSizeLong,
            &ChatReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ChatReq, _impl_._cached_size_),
        false,
    },
    &ChatReq::kDescriptorMethods,
    &descriptor_table_Chat_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ChatReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 27, 2> ChatReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::ChatReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string desc = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ChatReq, _impl_.desc_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string desc = 1;
    {PROTOBUF_FIELD_OFFSET(ChatReq, _impl_.desc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\4\0\0\0\0\0\0"
    "packet.ChatReq"
    "desc"
  }},
};

PROTOBUF_NOINLINE void ChatReq::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.ChatReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.desc_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ChatReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ChatReq& this_ = static_cast<const ChatReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ChatReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ChatReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.ChatReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string desc = 1;
          if (!this_._internal_desc().empty()) {
            const std::string& _s = this_._internal_desc();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.ChatReq.desc");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.ChatReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ChatReq::ByteSizeLong(const MessageLite& base) {
          const ChatReq& this_ = static_cast<const ChatReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ChatReq::ByteSizeLong() const {
          const ChatReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.ChatReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string desc = 1;
            if (!this_._internal_desc().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_desc());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ChatReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChatReq*>(&to_msg);
  auto& from = static_cast<const ChatReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.ChatReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_desc().empty()) {
    _this->_internal_set_desc(from._internal_desc());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChatReq::CopyFrom(const ChatReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.ChatReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChatReq::InternalSwap(ChatReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_, &other->_impl_.desc_, arena);
}

::google::protobuf::Metadata ChatReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ChatRes::_Internal {
 public:
};

ChatRes::ChatRes(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.ChatRes)
}
inline PROTOBUF_NDEBUG_INLINE ChatRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::ChatRes& from_msg)
      : desc_(arena, from.desc_),
        _cached_size_{0} {}

ChatRes::ChatRes(
    ::google::protobuf::Arena* arena,
    const ChatRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChatRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.errorcode_ = from._impl_.errorcode_;

  // @@protoc_insertion_point(copy_constructor:packet.ChatRes)
}
inline PROTOBUF_NDEBUG_INLINE ChatRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : desc_(arena),
        _cached_size_{0} {}

inline void ChatRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.errorcode_ = {};
}
ChatRes::~ChatRes() {
  // @@protoc_insertion_point(destructor:packet.ChatRes)
  SharedDtor(*this);
}
inline void ChatRes::SharedDtor(MessageLite& self) {
  ChatRes& this_ = static_cast<ChatRes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.desc_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ChatRes::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ChatRes(arena);
}
constexpr auto ChatRes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ChatRes),
                                            alignof(ChatRes));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ChatRes::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ChatRes_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ChatRes::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ChatRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ChatRes::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ChatRes>(), &ChatRes::ByteSizeLong,
            &ChatRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ChatRes, _impl_._cached_size_),
        false,
    },
    &ChatRes::kDescriptorMethods,
    &descriptor_table_Chat_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ChatRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 27, 2> ChatRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::ChatRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string desc = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ChatRes, _impl_.desc_)}},
    // .packet.ErrorCode errorCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ChatRes, _impl_.errorcode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ChatRes, _impl_.errorcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .packet.ErrorCode errorCode = 1;
    {PROTOBUF_FIELD_OFFSET(ChatRes, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string desc = 2;
    {PROTOBUF_FIELD_OFFSET(ChatRes, _impl_.desc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\4\0\0\0\0\0"
    "packet.ChatRes"
    "desc"
  }},
};

PROTOBUF_NOINLINE void ChatRes::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.ChatRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.desc_.ClearToEmpty();
  _impl_.errorcode_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ChatRes::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ChatRes& this_ = static_cast<const ChatRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ChatRes::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ChatRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.ChatRes)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .packet.ErrorCode errorCode = 1;
          if (this_._internal_errorcode() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_errorcode(), target);
          }

          // string desc = 2;
          if (!this_._internal_desc().empty()) {
            const std::string& _s = this_._internal_desc();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.ChatRes.desc");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.ChatRes)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ChatRes::ByteSizeLong(const MessageLite& base) {
          const ChatRes& this_ = static_cast<const ChatRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ChatRes::ByteSizeLong() const {
          const ChatRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.ChatRes)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string desc = 2;
            if (!this_._internal_desc().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_desc());
            }
            // .packet.ErrorCode errorCode = 1;
            if (this_._internal_errorcode() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_errorcode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ChatRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChatRes*>(&to_msg);
  auto& from = static_cast<const ChatRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.ChatRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_desc().empty()) {
    _this->_internal_set_desc(from._internal_desc());
  }
  if (from._internal_errorcode() != 0) {
    _this->_impl_.errorcode_ = from._impl_.errorcode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChatRes::CopyFrom(const ChatRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.ChatRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChatRes::InternalSwap(ChatRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_, &other->_impl_.desc_, arena);
  swap(_impl_.errorcode_, other->_impl_.errorcode_);
}

::google::protobuf::Metadata ChatRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ChatNot::_Internal {
 public:
};

ChatNot::ChatNot(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.ChatNot)
}
inline PROTOBUF_NDEBUG_INLINE ChatNot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::ChatNot& from_msg)
      : desc_(arena, from.desc_),
        _cached_size_{0} {}

ChatNot::ChatNot(
    ::google::protobuf::Arena* arena,
    const ChatNot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChatNot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sessionid_ = from._impl_.sessionid_;

  // @@protoc_insertion_point(copy_constructor:packet.ChatNot)
}
inline PROTOBUF_NDEBUG_INLINE ChatNot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : desc_(arena),
        _cached_size_{0} {}

inline void ChatNot::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sessionid_ = {};
}
ChatNot::~ChatNot() {
  // @@protoc_insertion_point(destructor:packet.ChatNot)
  SharedDtor(*this);
}
inline void ChatNot::SharedDtor(MessageLite& self) {
  ChatNot& this_ = static_cast<ChatNot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.desc_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ChatNot::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ChatNot(arena);
}
constexpr auto ChatNot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ChatNot),
                                            alignof(ChatNot));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ChatNot::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ChatNot_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ChatNot::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ChatNot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ChatNot::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ChatNot>(), &ChatNot::ByteSizeLong,
            &ChatNot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ChatNot, _impl_._cached_size_),
        false,
    },
    &ChatNot::kDescriptorMethods,
    &descriptor_table_Chat_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ChatNot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 27, 2> ChatNot::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::ChatNot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string desc = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ChatNot, _impl_.desc_)}},
    // uint64 sessionId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ChatNot, _impl_.sessionid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ChatNot, _impl_.sessionid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 sessionId = 1;
    {PROTOBUF_FIELD_OFFSET(ChatNot, _impl_.sessionid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string desc = 2;
    {PROTOBUF_FIELD_OFFSET(ChatNot, _impl_.desc_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\4\0\0\0\0\0"
    "packet.ChatNot"
    "desc"
  }},
};

PROTOBUF_NOINLINE void ChatNot::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.ChatNot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.desc_.ClearToEmpty();
  _impl_.sessionid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ChatNot::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ChatNot& this_ = static_cast<const ChatNot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ChatNot::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ChatNot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.ChatNot)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 sessionId = 1;
          if (this_._internal_sessionid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_sessionid(), target);
          }

          // string desc = 2;
          if (!this_._internal_desc().empty()) {
            const std::string& _s = this_._internal_desc();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.ChatNot.desc");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.ChatNot)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ChatNot::ByteSizeLong(const MessageLite& base) {
          const ChatNot& this_ = static_cast<const ChatNot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ChatNot::ByteSizeLong() const {
          const ChatNot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.ChatNot)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string desc = 2;
            if (!this_._internal_desc().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_desc());
            }
            // uint64 sessionId = 1;
            if (this_._internal_sessionid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_sessionid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ChatNot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChatNot*>(&to_msg);
  auto& from = static_cast<const ChatNot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.ChatNot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_desc().empty()) {
    _this->_internal_set_desc(from._internal_desc());
  }
  if (from._internal_sessionid() != 0) {
    _this->_impl_.sessionid_ = from._impl_.sessionid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChatNot::CopyFrom(const ChatNot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.ChatNot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChatNot::InternalSwap(ChatNot* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_, &other->_impl_.desc_, arena);
        swap(_impl_.sessionid_, other->_impl_.sessionid_);
}

::google::protobuf::Metadata ChatNot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Chat_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
