// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enums.proto
// Protobuf C++ Version: 5.29.3

#include "Enums.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace packet {
}  // namespace packet
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enums_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Enums_2eproto = nullptr;
const ::uint32_t TableStruct_Enums_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_Enums_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013Enums.proto\022\006packet*J\n\010Defaults\022\022\n\016DEF"
    "AULT_DEFINE\020\000\022\022\n\016NAME_MAX_LIMIT\020\014\022\026\n\021MES"
    "SAGE_MAX_LIMIT\020\364\003*\265\001\n\tErrorCode\022\006\n\002OK\020\000\022"
    "\010\n\004FAIL\020\001\022\030\n\024FAIL_ALREADY_IN_ROOM\020d\022\024\n\020F"
    "AIL_NOT_IN_ROOM\020e\022\023\n\017FAIL_EMPTY_NAME\020f\022\032"
    "\n\026FAIL_EXCEED_NAME_LIMIT\020g\022\035\n\031FAIL_EXCEE"
    "D_MESSAGE_LIMIT\020n\022\026\n\022FAIL_EMPTY_MESSAGE\020"
    "ob\006proto3"
};
static ::absl::once_flag descriptor_table_Enums_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Enums_2eproto = {
    false,
    false,
    289,
    descriptor_table_protodef_Enums_2eproto,
    "Enums.proto",
    &descriptor_table_Enums_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_Enums_2eproto::offsets,
    file_level_enum_descriptors_Enums_2eproto,
    file_level_service_descriptors_Enums_2eproto,
};
namespace packet {
const ::google::protobuf::EnumDescriptor* Defaults_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Enums_2eproto);
  return file_level_enum_descriptors_Enums_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Defaults_internal_data_[] = {
    65536u, 65568u, 2048u, 500u, };
bool Defaults_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, Defaults_internal_data_);
}
const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Enums_2eproto);
  return file_level_enum_descriptors_Enums_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ErrorCode_internal_data_[] = {
    131072u, 128u, 0u, 0u, 0u, 12348u, };
bool ErrorCode_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ErrorCode_internal_data_);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Enums_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
