// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Room.proto
// Protobuf C++ Version: 5.29.3

#include "Room.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace packet {

inline constexpr Player::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sessionid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Player::Player(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerDefaultTypeInternal() {}
  union {
    Player _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerDefaultTypeInternal _Player_default_instance_;

inline constexpr LeaveRoomRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : errorcode_{static_cast< ::packet::ErrorCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LeaveRoomRes::LeaveRoomRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LeaveRoomResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LeaveRoomResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LeaveRoomResDefaultTypeInternal() {}
  union {
    LeaveRoomRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LeaveRoomResDefaultTypeInternal _LeaveRoomRes_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR LeaveRoomReq::LeaveRoomReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct LeaveRoomReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LeaveRoomReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LeaveRoomReqDefaultTypeInternal() {}
  union {
    LeaveRoomReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LeaveRoomReqDefaultTypeInternal _LeaveRoomReq_default_instance_;

inline constexpr LeaveRoomNot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sessionid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LeaveRoomNot::LeaveRoomNot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LeaveRoomNotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LeaveRoomNotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LeaveRoomNotDefaultTypeInternal() {}
  union {
    LeaveRoomNot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LeaveRoomNotDefaultTypeInternal _LeaveRoomNot_default_instance_;

inline constexpr JoinRoomReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JoinRoomReq::JoinRoomReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JoinRoomReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JoinRoomReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JoinRoomReqDefaultTypeInternal() {}
  union {
    JoinRoomReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JoinRoomReqDefaultTypeInternal _JoinRoomReq_default_instance_;

inline constexpr JoinRoomRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : players_{},
        errorcode_{static_cast< ::packet::ErrorCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JoinRoomRes::JoinRoomRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JoinRoomResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JoinRoomResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JoinRoomResDefaultTypeInternal() {}
  union {
    JoinRoomRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JoinRoomResDefaultTypeInternal _JoinRoomRes_default_instance_;

inline constexpr JoinRoomNot::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        player_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR JoinRoomNot::JoinRoomNot(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JoinRoomNotDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JoinRoomNotDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JoinRoomNotDefaultTypeInternal() {}
  union {
    JoinRoomNot _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JoinRoomNotDefaultTypeInternal _JoinRoomNot_default_instance_;
}  // namespace packet
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Room_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Room_2eproto = nullptr;
const ::uint32_t
    TableStruct_Room_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::Player, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::Player, _impl_.sessionid_),
        PROTOBUF_FIELD_OFFSET(::packet::Player, _impl_.name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomReq, _impl_.name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomRes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomRes, _impl_.errorcode_),
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomRes, _impl_.players_),
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomNot, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomNot, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::JoinRoomNot, _impl_.player_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::LeaveRoomReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::LeaveRoomRes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::LeaveRoomRes, _impl_.errorcode_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::packet::LeaveRoomNot, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::packet::LeaveRoomNot, _impl_.sessionid_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::packet::Player)},
        {10, -1, -1, sizeof(::packet::JoinRoomReq)},
        {19, -1, -1, sizeof(::packet::JoinRoomRes)},
        {29, 38, -1, sizeof(::packet::JoinRoomNot)},
        {39, -1, -1, sizeof(::packet::LeaveRoomReq)},
        {47, -1, -1, sizeof(::packet::LeaveRoomRes)},
        {56, -1, -1, sizeof(::packet::LeaveRoomNot)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::packet::_Player_default_instance_._instance,
    &::packet::_JoinRoomReq_default_instance_._instance,
    &::packet::_JoinRoomRes_default_instance_._instance,
    &::packet::_JoinRoomNot_default_instance_._instance,
    &::packet::_LeaveRoomReq_default_instance_._instance,
    &::packet::_LeaveRoomRes_default_instance_._instance,
    &::packet::_LeaveRoomNot_default_instance_._instance,
};
const char descriptor_table_protodef_Room_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nRoom.proto\022\006packet\032\013Enums.proto\")\n\006Pla"
    "yer\022\021\n\tsessionId\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\"\033\n\013"
    "JoinRoomReq\022\014\n\004name\030\001 \001(\t\"T\n\013JoinRoomRes"
    "\022$\n\terrorCode\030\001 \001(\0162\021.packet.ErrorCode\022\037"
    "\n\007players\030\002 \003(\0132\016.packet.Player\"-\n\013JoinR"
    "oomNot\022\036\n\006player\030\001 \001(\0132\016.packet.Player\"\016"
    "\n\014LeaveRoomReq\"4\n\014LeaveRoomRes\022$\n\terrorC"
    "ode\030\001 \001(\0162\021.packet.ErrorCode\"!\n\014LeaveRoo"
    "mNot\022\021\n\tsessionId\030\001 \001(\004b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Room_2eproto_deps[1] =
    {
        &::descriptor_table_Enums_2eproto,
};
static ::absl::once_flag descriptor_table_Room_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Room_2eproto = {
    false,
    false,
    351,
    descriptor_table_protodef_Room_2eproto,
    "Room.proto",
    &descriptor_table_Room_2eproto_once,
    descriptor_table_Room_2eproto_deps,
    1,
    7,
    schemas,
    file_default_instances,
    TableStruct_Room_2eproto::offsets,
    file_level_enum_descriptors_Room_2eproto,
    file_level_service_descriptors_Room_2eproto,
};
namespace packet {
// ===================================================================

class Player::_Internal {
 public:
};

Player::Player(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.Player)
}
inline PROTOBUF_NDEBUG_INLINE Player::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::Player& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

Player::Player(
    ::google::protobuf::Arena* arena,
    const Player& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Player* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sessionid_ = from._impl_.sessionid_;

  // @@protoc_insertion_point(copy_constructor:packet.Player)
}
inline PROTOBUF_NDEBUG_INLINE Player::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void Player::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sessionid_ = {};
}
Player::~Player() {
  // @@protoc_insertion_point(destructor:packet.Player)
  SharedDtor(*this);
}
inline void Player::SharedDtor(MessageLite& self) {
  Player& this_ = static_cast<Player&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Player::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Player(arena);
}
constexpr auto Player::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Player),
                                            alignof(Player));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Player::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Player_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Player::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Player>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Player::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Player>(), &Player::ByteSizeLong,
            &Player::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Player, _impl_._cached_size_),
        false,
    },
    &Player::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Player::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 26, 2> Player::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::Player>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Player, _impl_.name_)}},
    // uint64 sessionId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Player, _impl_.sessionid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Player, _impl_.sessionid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 sessionId = 1;
    {PROTOBUF_FIELD_OFFSET(Player, _impl_.sessionid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(Player, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\4\0\0\0\0\0"
    "packet.Player"
    "name"
  }},
};

PROTOBUF_NOINLINE void Player::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.Player)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.sessionid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Player::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Player& this_ = static_cast<const Player&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Player::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Player& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.Player)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 sessionId = 1;
          if (this_._internal_sessionid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_sessionid(), target);
          }

          // string name = 2;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.Player.name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.Player)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Player::ByteSizeLong(const MessageLite& base) {
          const Player& this_ = static_cast<const Player&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Player::ByteSizeLong() const {
          const Player& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.Player)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 2;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // uint64 sessionId = 1;
            if (this_._internal_sessionid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_sessionid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Player::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Player*>(&to_msg);
  auto& from = static_cast<const Player&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.Player)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_sessionid() != 0) {
    _this->_impl_.sessionid_ = from._impl_.sessionid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Player::CopyFrom(const Player& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.Player)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Player::InternalSwap(Player* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
        swap(_impl_.sessionid_, other->_impl_.sessionid_);
}

::google::protobuf::Metadata Player::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JoinRoomReq::_Internal {
 public:
};

JoinRoomReq::JoinRoomReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.JoinRoomReq)
}
inline PROTOBUF_NDEBUG_INLINE JoinRoomReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::JoinRoomReq& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

JoinRoomReq::JoinRoomReq(
    ::google::protobuf::Arena* arena,
    const JoinRoomReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JoinRoomReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:packet.JoinRoomReq)
}
inline PROTOBUF_NDEBUG_INLINE JoinRoomReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void JoinRoomReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
JoinRoomReq::~JoinRoomReq() {
  // @@protoc_insertion_point(destructor:packet.JoinRoomReq)
  SharedDtor(*this);
}
inline void JoinRoomReq::SharedDtor(MessageLite& self) {
  JoinRoomReq& this_ = static_cast<JoinRoomReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* JoinRoomReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) JoinRoomReq(arena);
}
constexpr auto JoinRoomReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(JoinRoomReq),
                                            alignof(JoinRoomReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull JoinRoomReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_JoinRoomReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &JoinRoomReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<JoinRoomReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &JoinRoomReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<JoinRoomReq>(), &JoinRoomReq::ByteSizeLong,
            &JoinRoomReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(JoinRoomReq, _impl_._cached_size_),
        false,
    },
    &JoinRoomReq::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* JoinRoomReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2> JoinRoomReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::JoinRoomReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(JoinRoomReq, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(JoinRoomReq, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\4\0\0\0\0\0\0"
    "packet.JoinRoomReq"
    "name"
  }},
};

PROTOBUF_NOINLINE void JoinRoomReq::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.JoinRoomReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JoinRoomReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JoinRoomReq& this_ = static_cast<const JoinRoomReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JoinRoomReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JoinRoomReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.JoinRoomReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string name = 1;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "packet.JoinRoomReq.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.JoinRoomReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JoinRoomReq::ByteSizeLong(const MessageLite& base) {
          const JoinRoomReq& this_ = static_cast<const JoinRoomReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JoinRoomReq::ByteSizeLong() const {
          const JoinRoomReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.JoinRoomReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string name = 1;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JoinRoomReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JoinRoomReq*>(&to_msg);
  auto& from = static_cast<const JoinRoomReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.JoinRoomReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JoinRoomReq::CopyFrom(const JoinRoomReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.JoinRoomReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JoinRoomReq::InternalSwap(JoinRoomReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata JoinRoomReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JoinRoomRes::_Internal {
 public:
};

JoinRoomRes::JoinRoomRes(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.JoinRoomRes)
}
inline PROTOBUF_NDEBUG_INLINE JoinRoomRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::JoinRoomRes& from_msg)
      : players_{visibility, arena, from.players_},
        _cached_size_{0} {}

JoinRoomRes::JoinRoomRes(
    ::google::protobuf::Arena* arena,
    const JoinRoomRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JoinRoomRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.errorcode_ = from._impl_.errorcode_;

  // @@protoc_insertion_point(copy_constructor:packet.JoinRoomRes)
}
inline PROTOBUF_NDEBUG_INLINE JoinRoomRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : players_{visibility, arena},
        _cached_size_{0} {}

inline void JoinRoomRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.errorcode_ = {};
}
JoinRoomRes::~JoinRoomRes() {
  // @@protoc_insertion_point(destructor:packet.JoinRoomRes)
  SharedDtor(*this);
}
inline void JoinRoomRes::SharedDtor(MessageLite& self) {
  JoinRoomRes& this_ = static_cast<JoinRoomRes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* JoinRoomRes::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) JoinRoomRes(arena);
}
constexpr auto JoinRoomRes::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(JoinRoomRes, _impl_.players_) +
          decltype(JoinRoomRes::_impl_.players_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(JoinRoomRes), alignof(JoinRoomRes), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&JoinRoomRes::PlacementNew_,
                                 sizeof(JoinRoomRes),
                                 alignof(JoinRoomRes));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull JoinRoomRes::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_JoinRoomRes_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &JoinRoomRes::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<JoinRoomRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &JoinRoomRes::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<JoinRoomRes>(), &JoinRoomRes::ByteSizeLong,
            &JoinRoomRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(JoinRoomRes, _impl_._cached_size_),
        false,
    },
    &JoinRoomRes::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* JoinRoomRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> JoinRoomRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::JoinRoomRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .packet.Player players = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JoinRoomRes, _impl_.players_)}},
    // .packet.ErrorCode errorCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JoinRoomRes, _impl_.errorcode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JoinRoomRes, _impl_.errorcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .packet.ErrorCode errorCode = 1;
    {PROTOBUF_FIELD_OFFSET(JoinRoomRes, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated .packet.Player players = 2;
    {PROTOBUF_FIELD_OFFSET(JoinRoomRes, _impl_.players_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::packet::Player>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void JoinRoomRes::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.JoinRoomRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.players_.Clear();
  _impl_.errorcode_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JoinRoomRes::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JoinRoomRes& this_ = static_cast<const JoinRoomRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JoinRoomRes::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JoinRoomRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.JoinRoomRes)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .packet.ErrorCode errorCode = 1;
          if (this_._internal_errorcode() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_errorcode(), target);
          }

          // repeated .packet.Player players = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_players_size());
               i < n; i++) {
            const auto& repfield = this_._internal_players().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.JoinRoomRes)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JoinRoomRes::ByteSizeLong(const MessageLite& base) {
          const JoinRoomRes& this_ = static_cast<const JoinRoomRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JoinRoomRes::ByteSizeLong() const {
          const JoinRoomRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.JoinRoomRes)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .packet.Player players = 2;
            {
              total_size += 1UL * this_._internal_players_size();
              for (const auto& msg : this_._internal_players()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // .packet.ErrorCode errorCode = 1;
            if (this_._internal_errorcode() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_errorcode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JoinRoomRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JoinRoomRes*>(&to_msg);
  auto& from = static_cast<const JoinRoomRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.JoinRoomRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_players()->MergeFrom(
      from._internal_players());
  if (from._internal_errorcode() != 0) {
    _this->_impl_.errorcode_ = from._impl_.errorcode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JoinRoomRes::CopyFrom(const JoinRoomRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.JoinRoomRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JoinRoomRes::InternalSwap(JoinRoomRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.players_.InternalSwap(&other->_impl_.players_);
  swap(_impl_.errorcode_, other->_impl_.errorcode_);
}

::google::protobuf::Metadata JoinRoomRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class JoinRoomNot::_Internal {
 public:
  using HasBits =
      decltype(std::declval<JoinRoomNot>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JoinRoomNot, _impl_._has_bits_);
};

JoinRoomNot::JoinRoomNot(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.JoinRoomNot)
}
inline PROTOBUF_NDEBUG_INLINE JoinRoomNot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::packet::JoinRoomNot& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

JoinRoomNot::JoinRoomNot(
    ::google::protobuf::Arena* arena,
    const JoinRoomNot& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JoinRoomNot* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.player_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::packet::Player>(
                              arena, *from._impl_.player_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:packet.JoinRoomNot)
}
inline PROTOBUF_NDEBUG_INLINE JoinRoomNot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void JoinRoomNot::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.player_ = {};
}
JoinRoomNot::~JoinRoomNot() {
  // @@protoc_insertion_point(destructor:packet.JoinRoomNot)
  SharedDtor(*this);
}
inline void JoinRoomNot::SharedDtor(MessageLite& self) {
  JoinRoomNot& this_ = static_cast<JoinRoomNot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.player_;
  this_._impl_.~Impl_();
}

inline void* JoinRoomNot::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) JoinRoomNot(arena);
}
constexpr auto JoinRoomNot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(JoinRoomNot),
                                            alignof(JoinRoomNot));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull JoinRoomNot::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_JoinRoomNot_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &JoinRoomNot::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<JoinRoomNot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &JoinRoomNot::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<JoinRoomNot>(), &JoinRoomNot::ByteSizeLong,
            &JoinRoomNot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(JoinRoomNot, _impl_._cached_size_),
        false,
    },
    &JoinRoomNot::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* JoinRoomNot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> JoinRoomNot::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JoinRoomNot, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::JoinRoomNot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .packet.Player player = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(JoinRoomNot, _impl_.player_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .packet.Player player = 1;
    {PROTOBUF_FIELD_OFFSET(JoinRoomNot, _impl_.player_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::packet::Player>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void JoinRoomNot::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.JoinRoomNot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.player_ != nullptr);
    _impl_.player_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JoinRoomNot::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JoinRoomNot& this_ = static_cast<const JoinRoomNot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JoinRoomNot::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JoinRoomNot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.JoinRoomNot)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .packet.Player player = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.player_, this_._impl_.player_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.JoinRoomNot)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JoinRoomNot::ByteSizeLong(const MessageLite& base) {
          const JoinRoomNot& this_ = static_cast<const JoinRoomNot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JoinRoomNot::ByteSizeLong() const {
          const JoinRoomNot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.JoinRoomNot)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .packet.Player player = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.player_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JoinRoomNot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JoinRoomNot*>(&to_msg);
  auto& from = static_cast<const JoinRoomNot&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.JoinRoomNot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.player_ != nullptr);
    if (_this->_impl_.player_ == nullptr) {
      _this->_impl_.player_ =
          ::google::protobuf::Message::CopyConstruct<::packet::Player>(arena, *from._impl_.player_);
    } else {
      _this->_impl_.player_->MergeFrom(*from._impl_.player_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JoinRoomNot::CopyFrom(const JoinRoomNot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.JoinRoomNot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JoinRoomNot::InternalSwap(JoinRoomNot* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.player_, other->_impl_.player_);
}

::google::protobuf::Metadata JoinRoomNot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LeaveRoomReq::_Internal {
 public:
};

LeaveRoomReq::LeaveRoomReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:packet.LeaveRoomReq)
}
LeaveRoomReq::LeaveRoomReq(
    ::google::protobuf::Arena* arena,
    const LeaveRoomReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LeaveRoomReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:packet.LeaveRoomReq)
}

inline void* LeaveRoomReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LeaveRoomReq(arena);
}
constexpr auto LeaveRoomReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LeaveRoomReq),
                                            alignof(LeaveRoomReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LeaveRoomReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LeaveRoomReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LeaveRoomReq::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<LeaveRoomReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LeaveRoomReq::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<LeaveRoomReq>(), &LeaveRoomReq::ByteSizeLong,
            &LeaveRoomReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LeaveRoomReq, _impl_._cached_size_),
        false,
    },
    &LeaveRoomReq::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LeaveRoomReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> LeaveRoomReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::LeaveRoomReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata LeaveRoomReq::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LeaveRoomRes::_Internal {
 public:
};

LeaveRoomRes::LeaveRoomRes(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.LeaveRoomRes)
}
LeaveRoomRes::LeaveRoomRes(
    ::google::protobuf::Arena* arena, const LeaveRoomRes& from)
    : LeaveRoomRes(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LeaveRoomRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LeaveRoomRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.errorcode_ = {};
}
LeaveRoomRes::~LeaveRoomRes() {
  // @@protoc_insertion_point(destructor:packet.LeaveRoomRes)
  SharedDtor(*this);
}
inline void LeaveRoomRes::SharedDtor(MessageLite& self) {
  LeaveRoomRes& this_ = static_cast<LeaveRoomRes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* LeaveRoomRes::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LeaveRoomRes(arena);
}
constexpr auto LeaveRoomRes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LeaveRoomRes),
                                            alignof(LeaveRoomRes));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LeaveRoomRes::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LeaveRoomRes_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LeaveRoomRes::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LeaveRoomRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LeaveRoomRes::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LeaveRoomRes>(), &LeaveRoomRes::ByteSizeLong,
            &LeaveRoomRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LeaveRoomRes, _impl_._cached_size_),
        false,
    },
    &LeaveRoomRes::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LeaveRoomRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LeaveRoomRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::LeaveRoomRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .packet.ErrorCode errorCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LeaveRoomRes, _impl_.errorcode_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LeaveRoomRes, _impl_.errorcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .packet.ErrorCode errorCode = 1;
    {PROTOBUF_FIELD_OFFSET(LeaveRoomRes, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void LeaveRoomRes::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.LeaveRoomRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errorcode_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LeaveRoomRes::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LeaveRoomRes& this_ = static_cast<const LeaveRoomRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LeaveRoomRes::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LeaveRoomRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.LeaveRoomRes)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .packet.ErrorCode errorCode = 1;
          if (this_._internal_errorcode() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_errorcode(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.LeaveRoomRes)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LeaveRoomRes::ByteSizeLong(const MessageLite& base) {
          const LeaveRoomRes& this_ = static_cast<const LeaveRoomRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LeaveRoomRes::ByteSizeLong() const {
          const LeaveRoomRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.LeaveRoomRes)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .packet.ErrorCode errorCode = 1;
            if (this_._internal_errorcode() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_errorcode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LeaveRoomRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LeaveRoomRes*>(&to_msg);
  auto& from = static_cast<const LeaveRoomRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.LeaveRoomRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_errorcode() != 0) {
    _this->_impl_.errorcode_ = from._impl_.errorcode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LeaveRoomRes::CopyFrom(const LeaveRoomRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.LeaveRoomRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LeaveRoomRes::InternalSwap(LeaveRoomRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.errorcode_, other->_impl_.errorcode_);
}

::google::protobuf::Metadata LeaveRoomRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LeaveRoomNot::_Internal {
 public:
};

LeaveRoomNot::LeaveRoomNot(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:packet.LeaveRoomNot)
}
LeaveRoomNot::LeaveRoomNot(
    ::google::protobuf::Arena* arena, const LeaveRoomNot& from)
    : LeaveRoomNot(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LeaveRoomNot::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LeaveRoomNot::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sessionid_ = {};
}
LeaveRoomNot::~LeaveRoomNot() {
  // @@protoc_insertion_point(destructor:packet.LeaveRoomNot)
  SharedDtor(*this);
}
inline void LeaveRoomNot::SharedDtor(MessageLite& self) {
  LeaveRoomNot& this_ = static_cast<LeaveRoomNot&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* LeaveRoomNot::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LeaveRoomNot(arena);
}
constexpr auto LeaveRoomNot::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LeaveRoomNot),
                                            alignof(LeaveRoomNot));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LeaveRoomNot::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LeaveRoomNot_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LeaveRoomNot::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LeaveRoomNot>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LeaveRoomNot::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LeaveRoomNot>(), &LeaveRoomNot::ByteSizeLong,
            &LeaveRoomNot::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LeaveRoomNot, _impl_._cached_size_),
        false,
    },
    &LeaveRoomNot::kDescriptorMethods,
    &descriptor_table_Room_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LeaveRoomNot::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> LeaveRoomNot::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::packet::LeaveRoomNot>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 sessionId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LeaveRoomNot, _impl_.sessionid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LeaveRoomNot, _impl_.sessionid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 sessionId = 1;
    {PROTOBUF_FIELD_OFFSET(LeaveRoomNot, _impl_.sessionid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void LeaveRoomNot::Clear() {
// @@protoc_insertion_point(message_clear_start:packet.LeaveRoomNot)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sessionid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LeaveRoomNot::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LeaveRoomNot& this_ = static_cast<const LeaveRoomNot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LeaveRoomNot::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LeaveRoomNot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:packet.LeaveRoomNot)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 sessionId = 1;
          if (this_._internal_sessionid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_sessionid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:packet.LeaveRoomNot)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LeaveRoomNot::ByteSizeLong(const MessageLite& base) {
          const LeaveRoomNot& this_ = static_cast<const LeaveRoomNot&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LeaveRoomNot::ByteSizeLong() const {
          const LeaveRoomNot& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:packet.LeaveRoomNot)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 sessionId = 1;
            if (this_._internal_sessionid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_sessionid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LeaveRoomNot::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LeaveRoomNot*>(&to_msg);
  auto& from = static_cast<const LeaveRoomNot&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:packet.LeaveRoomNot)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sessionid() != 0) {
    _this->_impl_.sessionid_ = from._impl_.sessionid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LeaveRoomNot::CopyFrom(const LeaveRoomNot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet.LeaveRoomNot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LeaveRoomNot::InternalSwap(LeaveRoomNot* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sessionid_, other->_impl_.sessionid_);
}

::google::protobuf::Metadata LeaveRoomNot::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Room_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
