// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enums.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Packet {

  /// <summary>Holder for reflection information generated from Enums.proto</summary>
  public static partial class EnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for Enums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtFbnVtcy5wcm90bxIGcGFja2V0KkoKCERlZmF1bHRzEhIKDkRFRkFVTFRf",
            "REVGSU5FEAASEgoOTkFNRV9NQVhfTElNSVQQDBIWChFNRVNTQUdFX01BWF9M",
            "SU1JVBD0Ayq1AQoJRXJyb3JDb2RlEgYKAk9LEAASCAoERkFJTBABEhgKFEZB",
            "SUxfQUxSRUFEWV9JTl9ST09NEGQSFAoQRkFJTF9OT1RfSU5fUk9PTRBlEhMK",
            "D0ZBSUxfRU1QVFlfTkFNRRBmEhoKFkZBSUxfRVhDRUVEX05BTUVfTElNSVQQ",
            "ZxIdChlGQUlMX0VYQ0VFRF9NRVNTQUdFX0xJTUlUEG4SFgoSRkFJTF9FTVBU",
            "WV9NRVNTQUdFEG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Packet.Defaults), typeof(global::Packet.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Defaults {
    [pbr::OriginalName("DEFAULT_DEFINE")] DefaultDefine = 0,
    [pbr::OriginalName("NAME_MAX_LIMIT")] NameMaxLimit = 12,
    [pbr::OriginalName("MESSAGE_MAX_LIMIT")] MessageMaxLimit = 500,
  }

  public enum ErrorCode {
    [pbr::OriginalName("OK")] Ok = 0,
    [pbr::OriginalName("FAIL")] Fail = 1,
    [pbr::OriginalName("FAIL_ALREADY_IN_ROOM")] FailAlreadyInRoom = 100,
    [pbr::OriginalName("FAIL_NOT_IN_ROOM")] FailNotInRoom = 101,
    [pbr::OriginalName("FAIL_EMPTY_NAME")] FailEmptyName = 102,
    [pbr::OriginalName("FAIL_EXCEED_NAME_LIMIT")] FailExceedNameLimit = 103,
    [pbr::OriginalName("FAIL_EXCEED_MESSAGE_LIMIT")] FailExceedMessageLimit = 110,
    [pbr::OriginalName("FAIL_EMPTY_MESSAGE")] FailEmptyMessage = 111,
  }

  #endregion

}

#endregion Designer generated code
